services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: livraria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL:  jdbc:postgresql://db:5432/livraria
      DB_USER: postgres
      DB_PASS: root
    ports:
      - "8080:8080"

volumes:
  postgres-data:
