  spring:
    boot:
      docker:
        compose:
          lifecycle:
            enabled: false
    application:
      name: backend
    datasource:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/livraria}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:root}
    jpa:
      hibernate:
        ddl-auto: update
      open-in-view: false

